# Generated by Django 5.0 on 2024-02-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_registermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
